algoritmo "Salario_calculation"

  var
  
     A, b, c, d, f, g : real
     
     inicio
     
        escreval("Insira o total de horas trabalhadas")
        leia(A)
        
        escrevaL("Insira o valor da hora/aula")
        leia(b)
        
        escreval("Insira o percetual de desconto")
        leia(F)
        
        C := A*B
        
        D := (F/100)*C
        
        G := C-D
        
        escreva("Valor liquido:", G)
        
fimalgoritmo